### ISSUE TITLE
Swapped Color Data

### ISSUE THREAD

**Issue by yutokun** [Zorink/OpenPixelControl#2]
Thank you for the useful library!

What's the reason that color order in the `OpcClient.WriteFrame()` method is swapped?
RGB is correct in my environment.

**Comment by HunterCarlson** [comment]
I was wondering that myself when my lights weren't the right colors in RGB. I'm guessing I got a bad batch of leds?

Feel free to put in a pull req

**Comment by yutokun** [comment]
Thanks!
I made pull req. Please check it!
